
name: CI / CD
on: 
    pull_request:
        branches:
            - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.11"]
    env:
      PIPENV_IGNORE_VIRTUALENVS: 1
    steps:
      - uses: actions/checkout@v4
      - name: Install Python, pipenv and Pipfile packages
        uses: kojoru/prepare-pipenv@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name : Install pipenv
        run : pip install pipenv
      - name: Ensure Clean Dependency Setup
        run: |
          pipenv --rm || true  # Remove any pre-existing environment
          pipenv install --dev --skip-lock  # Install without locking
      - name: Debug Installed Dependencies
        run: pipenv graph  # Helps troubleshoot dependency issues

      #- name : Install dependacy 
      #  run : |
      #      pipenv install --dev --deploy
      #      pipenv install .
      #      pipenv run pip install -e .

      - name: Testing with pytest
        run: |
          pipenv install pytest
          pipenv run python -m pytest tests/
        env:
          PYTHONPATH: ${{ github.workspace }} 
  deliver:
            needs: [build]
            runs-on: ubuntu-latest
            timeout-minutes: 5
            env:
               PIPENV_IGNORE_VIRTUALENVS: 1
            steps:
              - uses: actions/checkout@v4
              - name: Install Python, pipenv and Pipfile packages
                uses: kojoru/prepare-pipenv@v1
              - name: Build package
                run: |
                  pipenv install build
                  pipenv run python -m build .
              - name: Publish to PyPI test server
                uses: pypa/gh-action-pypi-publish@release/v1
                with:
                  name: built-package
                  path: dist/