
name: CI / CD
on: 
    pull_request:
        branches:
            - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Install Python, pipenv and Pipfile packages
        uses: kojoru/prepare-pipenv@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name : Install pipenv
        run : pip install pipenv


      - name : Install dependacy 
        run : pipenv install --dev
              pipenv install .
      - name: Testing with pytest
        run: |
          pipenv install pytest
          pipenv run python -m pytest tests/

    